[build-system]
requires = ['setuptools==82.0.1']
build-backend = 'setuptools.build_meta'

[project]
name = 'un_data'
version = '0.0.1'

dependencies = [
    'requirements.txt'
]

dynamic = [
  'version'
]

[project.scripts]
<name of the entrypoint> = <path.to:function>
project_name = 'project_name.main:main'

[tool.setuptools.packages.find]
where = ['src']

[tool.setuptools_scm]
version_scheme = 'no-guess-dev'
local_scheme = 'no-local-version'
